/**
 * Regenerate src/raindrop-options.ts from the user's Raindrop account.
 *
 * A managed Notion database can only declare its select/multi_select options at
 * deploy time, so the Tags and Collection option lists are baked into a
 * generated module that `tsc` compiles into the deployed bundle. This script
 * fetches the current tags + collections and writes that module, then ensures
 * the worker exists and pushes the `.env` secrets (token, Gemini key, etc.) to
 * it. `bun run deploy` runs this first so the schema migrates with up-to-date
 * options. Bun auto-loads `.env`, so RAINDROP_TOKEN is already in process.env.
 */
import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { getAllTags, getCollections } from "../src/raindrop.ts";

const OPTIONS_PATH = "src/raindrop-options.ts";
const WORKER_NAME = "raindrop-notion-sync";

/** Notion option names can't contain commas; cap to Notion's 100-char limit. */
function sanitizeName(name: string): string {
  return name.replace(/,/g, " ").trim().slice(0, 100);
}

const token = process.env.RAINDROP_TOKEN;
if (!token) {
  console.error("RAINDROP_TOKEN is not set (expected in .env).");
  process.exit(1);
}

console.log("Fetching tags and collections from Raindrop…");
const [tags, collections] = await Promise.all([
  getAllTags(token),
  getCollections(token),
]);

// Tags become multi_select options. Drop comma-containing names (the wire
// format's option separator) and over-long names, then de-duplicate.
const tagOptions = [
  ...new Set(
    tags
      .map((t) => t.trim())
      .filter((t) => t.length > 0 && t.length <= 100 && !t.includes(",")),
  ),
].map((name) => ({ name }));

// Collections become select options, plus a fixed "Unsorted" bucket (id -1).
const collectionNameById: Record<string, string> = { "-1": "Unsorted" };
for (const c of collections) {
  collectionNameById[String(c._id)] = sanitizeName(c.title);
}
const collectionOptions = [...new Set(Object.values(collectionNameById))].map(
  (name) => ({ name }),
);

const module = `// AUTO-GENERATED by \`bun run refresh-options\` (run automatically by
// \`bun run deploy\`). Do not edit by hand.
//
// A managed Notion database can only declare its select / multi_select options
// at deploy time, so these are generated from your Raindrop account and
// compiled into the deployed bundle. This file is committed EMPTY upstream so
// the repository stays generic; your own deploy fills it in. It contains only
// tag/collection names — no secrets.
import type { SelectOption } from "@notionhq/workers/types";

/** Native \`Tags\` multi_select options (one per Raindrop tag). */
export const TAG_OPTIONS: SelectOption[] = ${JSON.stringify(tagOptions, null, 2)};

/** Native \`Collection\` select options (one per Raindrop collection). */
export const COLLECTION_OPTIONS: SelectOption[] = ${JSON.stringify(collectionOptions, null, 2)};

/** Maps a Raindrop collection id (as a string) to its display name. */
export const COLLECTION_NAMES: Record<string, string> = ${JSON.stringify(collectionNameById, null, 2)};
`;
writeFileSync(OPTIONS_PATH, module);
console.log(
  `Wrote ${tagOptions.length} tag + ${collectionOptions.length} collection options to ${OPTIONS_PATH}.`,
);

// Ensure the worker exists and its .env secrets are synced before deploy.
try {
  if (!existsSync("workers.json")) {
    console.log("No workers.json — creating the worker…");
    execSync(`bunx ntn workers create --name ${WORKER_NAME}`, { stdio: "inherit" });
  }
  console.log("Pushing .env secrets to the deployed worker…");
  execSync("bunx ntn workers env push --yes", { stdio: "inherit" });
} catch {
  console.warn(
    "Could not push env to a deployed worker (run `ntn login` / deploy once first). The options file is updated.",
  );
}
