// AUTO-GENERATED by `bun run refresh-options` (run automatically by
// `bun run deploy`). Do not edit by hand.
//
// A managed Notion database can only declare its select / multi_select options
// at deploy time, so these are generated from your Raindrop account and
// compiled into the deployed bundle. This file is committed EMPTY upstream so
// the repository stays generic; your own deploy fills it in. It contains only
// tag/collection names — no secrets.
import type { SelectOption } from "@notionhq/workers/types";

/** Native `Tags` multi_select options (one per Raindrop tag). */
export const TAG_OPTIONS: SelectOption[] = [];

/** Native `Collection` select options (one per Raindrop collection). */
export const COLLECTION_OPTIONS: SelectOption[] = [];

/** Maps a Raindrop collection id (as a string) to its display name. */
export const COLLECTION_NAMES: Record<string, string> = {};
